[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:sail

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:pulse]
command=php /var/www/html/artisan pulse:check
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/pulse.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/pulse.log
stderr_logfile_maxbytes=0

[program:scheduler]
command=php /var/www/html/artisan schedule:work
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/scheduler.log
stderr_logfile_maxbytes=0

[program:queue-health-worker]
command=php /var/www/html/artisan queue:work --queue=health --sleep=3 --tries=3 --timeout=30
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile_maxbytes=0

[program:queue-worker-1]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=300
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile_maxbytes=0

[program:queue-worker-2]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=300
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile_maxbytes=0

[program:queue-worker-3]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=300
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile_maxbytes=0

[program:queue-worker-4]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=300
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile_maxbytes=0
